### ISSUE TITLE
How to implement communication between parent-child components and sibling components? Are there examples?

### ISSUE THREAD

**Issue by xygit** [smalllong/lightue#2]
How to implement communication between parent-child components and sibling components? Are there examples?

**Comment by smalllong** [comment]
That's a good question.
For a quick answer, currently Lightue apps are just plain javascript, so you can try to use any valid javascript ways to implement communication. For example, when calling a factory function component, you can pass params and use them directly in the component's VDomSrc or as the initial state of the component; or directly use parent's state in child's VDomSrc. You can also try to use the native EventTarget() or other third party libraries to implement communication between different components.
The docs for components guides and its best practices are still to be written in future

**Comment by smalllong** [comment]
That's a good question.

For a quick answer, currently Lightue apps are just plain javascript, so you can try to use any valid javascript ways to implement communication. For example, when calling a factory function component, you can pass params and use them directly in the component's VDomSrc or as the initial state of the component; or directly use parent's state in child's VDomSrc. You can also try to use the native EventTarget() or other third party event bus libraries to implement communication between different components.

The docs for components guides and its best practices are still to be written in future

**Comment by xygit** [comment]
Thank you for your reply. My temporary solution is to hand over the state processing of the child component and the display of the view object to the control of the parent component, that is, the design idea of control inversion, looking forward to your case

**Comment by smalllong** [comment]
Closing this issue as the doc for components has been added. For sibling components communication I think it's out of Lightue's scope
